name: Build Dev

on:
  repository_dispatch:
    types: [build_dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout your master repo
    - name: Checkout Kuroba
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/Kuroba
        path: Kuroba
        fetch-depth: 0
        
    - name: Checkout Kuroba-dev
      uses: actions/checkout@v2
      with:
        path: Kuroba-dev
        fetch-depth: 0
        
    - name: Push release commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: Kuroba-dev

    # Get the SHA for the most recent commit in your master repo
    # Trim the commit SHA to be 8 characters long for the release
    # Get the version tag of the most recent release in your master repo
    - name: Generate Git Info
      id: get-info
      run: |
        echo "::set-output name=SHA::$(git rev-parse HEAD)"
        echo "::set-output name=tag::$(git rev-parse HEAD | cut -c1-8)"
        echo "::set-output name=version::$(git describe --abbrev=0 --tags)"
      working-directory: ./Kuroba
        
    
    # Set up the Java/JDK for the build, mostly for gradle
    - name: Set up Java 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    
    # Set up any Android SDK dependencies
    - name: Install Android Libraries
      uses: maxim-lobanov/setup-android-tools@v1
      with:
        packages: |
          platforms;android-32
          build-tools;30.0.3
          extras;android;m2repository
          ndk;22.1.7171670
        cache: true
        
    # Build the android project
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          assembleDevDebug
          --console plain
          -x lint
        build-root-directory: ./Kuroba/Kuroba
      
    # Store the location of the generated APK and build name
    - name: Setup outputs
      id: outputs
      run: |
        echo "::set-output name=output_apk::$(find -name "*.apk")"
        echo "::set-output name=app-name::$(find -name "*.apk" | xargs basename | sed 's/\.apk//')"
        
    # Create and get the SHA for the most recent commit in the dev repo
    - name: Create Release commit
      id: git-commit
      run: |
        git config --global user.email "Adamantcheese@users.noreply.github.com"
        git config --global user.name "Adamantcheese"
        git commit --allow-empty -m "Release commit"
        echo "::set-output name=commitish::$(git rev-parse HEAD)"
      working-directory: ./Kuroba-dev
        
    # Create a release in this repository with a tag name of <release_version>-<trimmed_SHA> and a body of the full commit SHA
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: ${{ steps.get-info.outputs.version }}-${{ steps.get-info.outputs.tag }}
        tag_name: ${{ steps.get-info.outputs.version }}-${{ steps.get-info.outputs.tag }}
        body: ${{ steps.get-info.outputs.SHA }}
        commitish: ${{ steps.git-commit.outputs.commitish }}
     
    # Upload the generated APK from the build step to the URL generated by the create release step, renaming the APK to be <name>-<trimmed_SHA>.apk
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.outputs.outputs.output_apk }}
        asset_name: ${{ steps.outputs.outputs.app-name }}-${{ steps.get-info.outputs.tag }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 25
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
